import { IQuestion } from "./types";

export const questionData: IQuestion[] = [
  {
    id: 1,
    title: "Question 1 for EI",
    answerA: "Answer for E",
    answerB: "Answer for I",
    type: "EI",
  },
  {
    id: 2,
    title: "Question 2 for EI",
    answerA: "Answer for E",
    answerB: "Answer for I",
    type: "EI",
  },
  {
    id: 3,
    title: "Question 3 for EI",
    answerA: "Answer for E",
    answerB: "Answer for I",
    type: "EI",
  },
  {
    id: 4,
    title: "Question 1 for SN",
    answerA: "Answer for S",
    answerB: "Answer for N",
    type: "SN",
  },
  {
    id: 5,
    title: "Question 2 for SN",
    answerA: "Answer for S",
    answerB: "Answer for N",
    type: "SN",
  },
  {
    id: 6,
    title: "Question 3 for SN",
    answerA: "Answer for S",
    answerB: "Answer for N",
    type: "SN",
  },
  {
    id: 7,
    title: "Question 1 for FT",
    answerA: "Answer for F",
    answerB: "Answer for T",
    type: "FT",
  },
  {
    id: 8,
    title: "Question 2 for FT",
    answerA: "Answer for F",
    answerB: "Answer for T",
    type: "FT",
  },
  {
    id: 9,
    title: "Question 3 for FT",
    answerA: "Answer for F",
    answerB: "Answer for T",
    type: "FT",
  },
  {
    id: 10,
    title: "Question 1 for PJ",
    answerA: "Answer for P",
    answerB: "Answer for J",
    type: "PJ",
  },
  {
    id: 11,
    title: "Question 2 for PJ",
    answerA: "Answer for P",
    answerB: "Answer for J",
    type: "PJ",
  },
  {
    id: 12,
    title: "Question 3 for PJ",
    answerA: "Answer for P",
    answerB: "Answer for J",
    type: "PJ",
  },
];
